Style/FrozenStringLiteralComment:
  Enabled: false
Metrics/LineLength:
  Max: 160
Lint/AmbiguousBlockAssociation:
  Enabled: false
Lint/UnusedMethodArgument:
  Enabled: false
Naming/UncommunicativeMethodParamName:
  Enabled: false
Metrics/MethodLength:
  Max: 30
